"""
Render config.yaml from estimates/estimates.json (+ hand-entered bet details).

Run once after estimation:  python -m estimation.write_config
config.yaml is then the single source of truth and can be edited by hand.
tau comes from estimates/tau.json if present, otherwise the prompt's placeholders.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EST = json.load(open(ROOT / "estimates" / "estimates.json"))
TAU_FILE = ROOT / "estimates" / "tau.json"
TAU = json.load(open(TAU_FILE))["positions"] if TAU_FILE.exists() else None
PLACEHOLDER_TAU = {"QB": 0.11, "WR": 0.20, "TE": 0.22}

PLAYERS = [
    {"name": "Kyler Murray", "position": "QB", "team": "MIN", "stat": "passing_yards", "line": 3049.5},
    {"name": "Christian Watson", "position": "WR", "team": "GB", "stat": "receiving_yards", "line": 799.5},
    {"name": "DeVonta Smith", "position": "WR", "team": "PHI", "stat": "receiving_yards", "line": 1099.5},
    {"name": "Juwan Johnson", "position": "TE", "team": "NO", "stat": "receiving_yards", "line": 599.5},
]


def fmt_list(v):
    return "[" + ", ".join(f"{x:.5f}" for x in v) + "]"


def main():
    pulled = EST["pulled"]
    lines = [
        "# GOAT WHALE model configuration.",
        "# Generated by `python -m estimation.write_config` from estimates/estimates.json; safe to hand-edit.",
        "# Every parameter's source is noted inline.  Full detail: ASSUMPTIONS.md.",
        "",
        "bet:",
        "  stake: 1750.00          # $ staked on the reference ticket (from the bet slip)",
        "  profit: 23245.79        # $ profit if all 4 legs hit (from the bet slip) -> decimal payout 14.283309",
        "  example_stake: 250.00   # example bet size for the EV line in the output",
        "",
        "season_games: 17          # 2026 NFL regular season",
        "",
        "simulation:",
        "  n_sims: 100000          # simulated seasons per update (spec minimum 50,000)",
        "  seed: 20260916          # fixed seed; the same draws are reused across calibration and updates (common random numbers)",
        "  n_grid: 300             # grid points for the mu posterior (spec)",
        "",
        "players:                  # half-point lines; a leg hits if season total > line",
    ]
    for p in PLAYERS:
        lines += [f"  - name: {p['name']}", f"    position: {p['position']}", f"    team: \"{p['team']}\"",
                  f"    stat: {p['stat']}", f"    line: {p['line']}"]
    lines += ["", "positions:"]
    for pos in ("QB", "WR", "TE"):
        cv = EST["cv"][pos]
        hz = EST["hazard"][pos]
        pq = EST["p_questionable_plays"][pos]
        ab = EST["absence"][pos]
        qa = EST["q_absence"]["pooled"]
        ir = EST["ir_stint"]["pooled_conditional_ge4"]
        if TAU is not None and pos in TAU and TAU[pos].get("tau") is not None:
            tau_val, tau_src = TAU[pos]["tau"], (f"estimated from archived FantasyPros preseason consensus projections "
                                                 f"({TAU[pos]['n_player_seasons']} player-seasons, seasons {TAU[pos]['seasons']}); see ASSUMPTIONS.md")
        else:
            tau_val, tau_src = PLACEHOLDER_TAU[pos], "PLACEHOLDER from the prompt (no historical lines/projections available)"
        lines += [
            f"  {pos}:",
            f"    # per-game CV curve: log c = cv_log_a + cv_log_b * log(mu).  Fit by weighted least squares on",
            f"    # {cv['n_player_seasons']} player-seasons / {cv['n_games']} full healthy games, nflverse 2018-2025 (pulled {pulled}).",
            f"    # implied CV at mu = {', '.join(f'{k}: {v:.3f}' for k, v in cv['cv_at'].items())}",
            f"    cv_log_a: {cv['a']:.6f}",
            f"    cv_log_b: {cv['b']:.6f}",
            f"    # prior log-SD of the healthy rate: {tau_src}",
            f"    tau: {tau_val:.4f}",
            f"    # per-game injury hazard: {hz['n_events']} injury absences / {hz['n_exposure_games']} played games of {pos} regulars, nflverse 2018-2025",
            f"    hazard: {hz['h']:.5f}",
            f"    # P(plays | listed Questionable): {pq['n']} Questionable player-weeks of {pos} regulars, nflverse injuries 2018-2025",
            f"    p_questionable_plays: {pq['p']:.4f}",
            f"    # absence length after a simulated injury: Kaplan-Meier P(L=1..17 games), last cell = season-ending.",
            f"    # {ab['n']} {pos} injury absences ({ab['n_censored']} right-censored), nflverse 2018-2025",
            f"    absence_pmf: {fmt_list(ab['pmf'])}",
            f"    # absence length when a Questionable player sits (pooled QB/WR/TE, {qa['n']} absences, {qa['n_censored']} censored)",
            f"    q_absence_pmf: {fmt_list(qa['pmf'])}",
            f"    # IR stint length conditional on >= 4 games (pooled QB/WR/TE, seasons 2022-2025, {ir['n']} stints, {ir['n_censored']} censored)",
            f"    ir_pmf: {fmt_list(ir['pmf'])}",
        ]
    (ROOT / "config.yaml").write_text("\n".join(lines) + "\n")
    print("wrote config.yaml (tau source:", "estimates/tau.json" if TAU else "placeholders", ")")


if __name__ == "__main__":
    main()
